chat: main_r.cpp
	g++ -std=c++11 -Wall -o chat main_r.cpp

counting: counting.cpp
	g++ -std=c++17 -Wall -o counting counting.cpp

nested: nested.cpp
	g++ -std=c++17 -Wall -o nested nested.cpp

map_perf: map_performance.cpp
	g++ -std=c++17 -Wall -o map_perf map_performance.cpp

fruits: fruits.cpp
	g++ -std=c++17 -Wall -o fruits fruits.cpp

fruits_solution:
	g++ -std=c++17 -Wall -o fruits fruits_solution.cpp
